### ISSUE TITLE
[REQUEST] Advanced Season Stats for All Positions

### ISSUE THREAD

**Issue by nolmacdonald** [NuclearAnalyticsLab/nuclearff#10]
## REASON

Pulling advanced stats for offensive positions will allow for creating a dataframe with a complete overview on players performance throughout the season. Functions to create data frames for QB/RB/WR/TE will allow for future development on analyses, figures, tables, etc. with minimal data manipulation and/or wrangling.

## DESIGN

Utilize functions from `nflreadr` to pull advanced stats for offensive positions QB/RB/WR/TE.
- NFL Next Gen Stats (NGS) for "passing", "rushing" and "receiving"
  - Reference: [nflreadr `nflreadr::load_nextgen_stats`](https://nflreadr.nflverse.com/reference/load_nextgen_stats.html)
  - Reference: [NFL Next Gen Stats Glossary](https://nextgenstats.nfl.com/glossary)
- Pro Football Reference (PFR) advanced stats for "pass", "rush", "rec" - may need to add "def" later
  - `summary_level = "season"` for season stats (for now, add weeks later)
  - Reference: [nflreadr `nflreadr::load_pfr_advstats`](https://nflreadr.nflverse.com/reference/load_pfr_advstats.html)
  - Reference: [Data Dictionary - PFR Passing](https://nflreadr.nflverse.com/articles/dictionary_pfr_passing.html)
  - Reference: [PFR 2024 NFL Advanced Rushing](https://www.pro-football-reference.com/years/2024/rushing_advanced.htm)
  - Reference: [PFR 2024 NFL Advanced Receiving](https://www.pro-football-reference.com/years/2024/receiving_advanced.htm)
- Create function documentation with `roxygen2`
- Combine positional season stats from play-by-play data, NGS, and PFR into a single dataframe
  - NOTE: There may be some overlapping stats that need to be removed. Ensure there are no identical columns of stats and document the full naming scheme.

See more information on nflreadr functions in [nflreadr Package Index](https://nflreadr.nflverse.com/reference/index.html).

## IMPACT

This will add new functionality on obtaining player advanced stats. In addition, it will build upon obtaining play-by-play data and combining it with advanced stats for a complete overview of player stats for a season.

## ROADMAP

- [ ] Create function for pulling QB NFL NGS
- [ ] Create function for pulling RB NFL NGS
- [ ] Create function for pulling WR NFL NGS
- [ ] Create function for pulling TE NFL NGS
- [ ] Create function for pulling QB PFR Advanced Stats
- [ ] Create function for pulling RB PFR Advanced Stats
- [ ] Create function for pulling WR PFR Advanced Stats
- [ ] Create function for pulling TE PFR Advanced Stats
- [ ] Create function to combine QB play-by-play stats, NFL NGS, and PFR advanced stats
- [ ] Create function to combine RB play-by-play stats, NFL NGS, and PFR advanced stats
- [ ] Create function to combine WR play-by-play stats, NFL NGS, and PFR advanced stats
- [ ] Create function to combine TE play-by-play stats, NFL NGS, and PFR advanced stats
