### ISSUE TITLE
[REQUEST] Fantasy Football Standings Figures

### ISSUE THREAD

**Issue by nolmacdonald** [NuclearAnalyticsLab/nuclearff#11]
## REASON

This will allow for rapidly creating figures and tables for QB/RB/WR/TE that list fantasy football standings.
See [gt Tables documentation](https://gt.rstudio.com) for more information.

## DESIGN

- Pull player data for QB/RB/WR/TE with existing functions
- Create fantasy football standings by position with `gt` tables
- Utilize `gtExtras` for formatting and themes
  - Reference: [gtExtras Documentation](https://jthomasmock.github.io/gtExtras/)
  - Reference: [The MockUp - Hulk data_color](https://themockup.blog/posts/2022-06-13-gtextras-cran/)

## IMPACT

This will add the addition of rapidly creating figures for fantasy football standings with `gt`.

## ROADMAP

- [ ] Pull player data for QB/RB/WR/TE with existing functions
- [ ] Create fantasy football standings by position with `gt` tables
- [ ] Utilize `gtExtras` for formatting and themes
- [ ] Document functions with `roxygen2`
- [ ] Create additional tables or variants of tables (e.g., could be top 12, top 24 or another table for all flex players (RB/WR/TE)
