### ISSUE TITLE
[REQUEST] Fantasy Positional Weekly Stats

### ISSUE THREAD

**Issue by nolmacdonald** [NuclearAnalyticsLab/nuclearff#16]
## REASON

The package currently allows for pulling stats cumulatively based on a season.
New functions should be implemented that allow capabilities to pull individual weeks.
With individual weeks, a table can be developed that lists the fantasy points weekly with `gt`.
This would allow for a similar figure to the overall standings by QB/RB/WR/TE, except
that it doesn't list the stats for the season, but rather the weekly points.
For example, WR could have columns for Week 1 FPTS, Week 2 FPTS, ... Week N FPTS, and Total FPTS.
Order by Total.

## DESIGN

- [ ] Functions to calculate weekly fantasy points for QB/RB/WR/TE
- [ ] Functions to calculate season fantasy points while listing results for each week
- [ ] Table (figure) that lists fantasy points weekly for each position

## IMPACT

Adds new function to evaluate weekly performance not just season.

## ROADMAP

- Functions need to be developed and added
- Documentation is required
- Follow the tidyverse style guide
